# Generated by Django 5.1.7 on 2025-04-14 21:05

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='chatbot_data',
        ),
        migrations.RemoveField(
            model_name='chatbotdata',
            name='bm25_index',
        ),
        migrations.RemoveField(
            model_name='chatbotdata',
            name='embeddings',
        ),
        migrations.RemoveField(
            model_name='chatbotdata',
            name='faiss_index',
        ),
        migrations.AddField(
            model_name='chatbotdata',
            name='bm25_index_binary',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='chatbotdata',
            name='chatbot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='api.chatbot'),
        ),
        migrations.AddField(
            model_name='chatbotdata',
            name='embedding_model_name',
            field=models.CharField(default='all-MiniLM-L6-v2', max_length=100),
        ),
        migrations.AddField(
            model_name='chatbotdata',
            name='faiss_index_binary',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='chatbotdata',
            name='intent_labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='chatbotdocument',
            name='original_filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatbotdocument',
            name='tokenized_text',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='chatbotdocument',
            name='processed_text',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='api.chatbotdocument')),
            ],
        ),
    ]
