# Generated by Django 5.1.7 on 2025-06-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_intervened',
            field=models.BooleanField(default=False),
        ),
    ]
